### ISSUE TITLE
Error in xmlbuilder >=11 'Invalid character in name: fileVersion'

### ISSUE THREAD

**Issue by valery-vitko** [protobi/msexcel-builder#16]
When using xmlbuilder v11 or later document generation fails with the following error:

```
     Error: Invalid character in name: fileVersion
      at XMLStringifier.assertLegalName (node_modules/xmlbuilder/lib/XMLStringifier.js:239:17)
      at XMLStringifier.name (node_modules/xmlbuilder/lib/XMLStringifier.js:46:21)
      at new XMLElement (node_modules/xmlbuilder/lib/XMLElement.js:30:36)
      at XMLElement.node (node_modules/xmlbuilder/lib/XMLNode.js:292:17)
      at XMLElement.element (node_modules/xmlbuilder/lib/XMLNode.js:187:30)
      at XMLElement.ele (node_modules/xmlbuilder/lib/XMLNode.js:611:21)
      at XlWorkbook.toxml (lib/msexcel-builder.js:153:10)
      at Workbook.generate (lib/msexcel-builder.js:926:43)
```

**Comment by tcerven-emory** [comment]
Same problem
